baseURL = "https://www.benjamin-collet.fr/"
languageCode = "fr-fr"
title = "Benjamin Collet"

[params]
    Name = "Benjamin Collet"
    HeaderUsername = "benjamin"
    HeaderHostname = "stephano"
    About = "Hi, I'm Benjamin and this is my website. I am a developer, specialized in operations research."
    ProfilePicture = "/profile.jpg"
    GithubID = "TheMrBen"
    LinkedInID = "benjamin-collet"
    Email = "benjamin.collet@protonmail.ch"
    CvURL = "https://github.com/TheMrBen/curriculum-vitae"

[menu]
    [[menu.header]]
        identifier = "cv"
        name = "cv.pdf"
        weight = 1
        url = "/cv_benjamin_collet.pdf"
    [[menu.header]]
        identifier = "internship"
        name = "stages"
        weight = 0
    [[menu.header]]
        parent = "internship"
        name = "dut.pdf"
        url = "/traducteur_protothetique-gallina.pdf"
    [[menu.header]]
        parent = "internship"
        name = "master_1.pdf"
        url = "/modeling_of_tree_topology_using_coq.pdf"
