baseURL = "https://www.benjamin-collet.fr/"
languageCode = "fr-fr"
title = "Benjamin Collet"

[params]
    Name = "Benjamin Collet"
    HeaderUsername = "benjamin"
    HeaderHostname = "callirrhoe"
    ProfilePicture = "/profile.jpg"
    GithubID = "TheMrBen"
    LinkedInID = "benjamin-collet"
    Email = "benjamin.collet@protonmail.ch"
    CvURL = "https://github.com/TheMrBen/curriculum-vitae"
    About = "Récemment diplômé de l'Université Grenoble Alpes et de l'Ensimag, je suis titulaire d'un Master en Recherche Opérationnelle et Optimisation. Passionné par les algorithmes, je me suis orienté vers ce domaine pour les challenges qu'il propose. J'ai eu l'occasion de mettre en application ces connaissances lors de mon stage de fin d'étude chez LocalSolver, une entreprise renommée du secteur. Mon passage par un DUT et un Erasmus m'ont apporté des connaissances pratiques et une ouverture à la multiculturalité. Ce parcours inhabituel m'a permis d'acquérir des compétences appréciées par l’industrie."

[menu]
    [[menu.header]]
        identifier = "cv"
        name = "cv.pdf"
        weight = 1
        url = "/cv_benjamin_collet.pdf"
    [[menu.header]]
        identifier = "internship"
        name = "stages"
        weight = 0
    [[menu.header]]
        parent = "internship"
        name = "dut.pdf"
        url = "/traducteur_protothetique-gallina.pdf"
    [[menu.header]]
        parent = "internship"
        name = "master_1.pdf"
        url = "/modeling_of_tree_topology_using_coq.pdf"
    [[menu.header]]
        parent = "internship"
        name = "master_2.pdf"
        url = "/lower_bounds_computation_on_collections_based_models.pdf"
